# FROM python:3.10

# # Set working directory
# WORKDIR /app

# # Install required packages
# RUN pip install Flask requests google-generativeai pymongo

# # Copy source code
# COPY app /app

# # Expose port 5001
# EXPOSE 5001

# # Command to run the application
# CMD ["python", "bookshop.py"]
