# This is a basic workflow to help you get started with Actions

name: CICD

on:
  push:
    branches: [ ci ]
  pull_request:

env:
  IMAGE_NAME: frontend
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t $IMAGE_NAME .

